project:
  type: website
  output-dir: docs

website:
  title: "Bass Pond"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: default
    toc: true